server:
  port: 8096

spring:
  datasource:
    url: jdbc:h2:mem:bookingdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Activation du Circuit Breaker resilience4j sur les clients Feign
feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
    instances:
      class-service:
        base-config: default
      payment-service:
        base-config: default
      notification-service:
        base-config: default

logging:
  level:
    feign: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: DEBUG
